#!/usr/bin/env python

import shutil
import sys

import dox

def main():
    if not shutil.rmtree.avoids_symlink_attacks:
        sys.stderr.write((
            'The rmtree function on this system is vulnerable to symlink '
            'attacks, exiting.'
        ))
        sys.exit(-1)

    if len(sys.argv) != 2:
        print("Usage: dox [root folder]", file=sys.stderr)
        sys.exit(-1)

    folders = dox.Folders(sys.argv[1])

    folders.clear_doc_dir()
    folders.create_all()
    resources = dox.Resources(folders)
    resources.install()
    renderer = dox.Renderer(folders, resources)
    renderer.render_all()

main()
