#!/usr/bin/env python

import argparse
import shutil
import sys

import dox

def main():
    if not shutil.rmtree.avoids_symlink_attacks:
        sys.stderr.write((
            'The rmtree function on this system is vulnerable to symlink '
            'attacks, exiting.'
        ))
        sys.exit(-1)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        'working_folder', type=str, help='Path to working folder'
    )

    args = parser.parse_args()

    folders = dox.Folders(args.working_folder)

    folders.clear_doc_dir()
    folders.create_all()

    resources = dox.Resources(folders)
    resources.install()

    renderer = dox.Renderer(folders, resources)
    renderer.render_all()

main()
